#!/usr/bin/env node
/**
 * dashboard-slice.test.cjs — proves the visual slice cannot lie.
 *
 * These are static assertions over the slice's source. They are deliberately
 * crude and deliberately paranoid, because the failure they guard against is
 * not a crash — it is a dashboard that looks healthy while the system is not.
 * A timer-driven pulse, a hardcoded "PASS", or a seeded fallback object would
 * all render beautifully and mean nothing.
 *
 * Browser behaviour (real render, failure path, contrast, responsive) is
 * verified separately and recorded in the evidence report; these tests hold the
 * invariants that must never regress unnoticed between those sessions.
 */
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const DIR = path.join(ROOT, 'builder-control', 'dashboard');
const HTML_PATH = path.join(DIR, 'index.html');
const STATE_PATH = path.join(DIR, 'state.js');
// Read fresh each time: a cached copy would let a proof pass against a page
// that no longer exists on disk.
const htmlSrc = () => fs.readFileSync(HTML_PATH, 'utf8');

let passed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log(`ok   ${name}`); }
  catch (e) { console.error(`FAIL ${name}: ${e.message}`); process.exitCode = 1; }
}

const html = fs.readFileSync(HTML_PATH, 'utf8');
// Strip comments so a rule that *describes* a ban is not mistaken for breaking it.
const code = html.replace(/<!--[\s\S]*?-->/g, '').replace(/\/\*[\s\S]*?\*\//g, '');

console.log('AEGIS dashboard slice — invariants');

// ── nothing may animate on a timer ──────────────────────────────────────────
test('no timers anywhere: a pulse that can run without a real event is fake activity', () => {
  for (const banned of ['setInterval', 'setTimeout', 'requestAnimationFrame']) {
    assert.ok(!new RegExp('\\b' + banned + '\\s*\\(').test(code),
      `${banned}( found in executable code — motion must be bound to state, not to time`);
  }
});

test('the only animation is bound to a real ACTIVE state', () => {
  const keyframes = code.match(/@keyframes\s+([\w-]+)/g) || [];
  assert.strictEqual(keyframes.length, 1, `expected exactly 1 keyframes block, found ${keyframes.length}`);
  assert.ok(/\.stage\.is-active\s+\.dot\s*\{[^}]*animation/.test(code),
    'the single animation must be gated on .is-active, which is set only from state');
});

test('reduced motion is honoured and removes the animation', () => {
  assert.ok(/@media\s*\(prefers-reduced-motion:\s*reduce\)/.test(code), 'no reduced-motion block');
  const block = code.slice(code.indexOf('prefers-reduced-motion'));
  assert.ok(/animation\s*:\s*none/.test(block.slice(0, 400)), 'reduced motion must disable the animation');
});

// ── one data path, no seeds ─────────────────────────────────────────────────
test('the slice reads window.AEGIS_STATE and has no fallback seed object', () => {
  assert.ok(/window\.AEGIS_STATE/.test(code), 'must read the projector output');
  assert.ok(!/AEGIS_STATE\s*\|\|\s*\{/.test(code),
    'a `|| {}` fallback would let the page render confidently with no real state');
  assert.ok(/AEGIS_STATE\s*\|\|\s*null/.test(code), 'absence must resolve to null and be handled explicitly');
});

test('state.js is generated, never hand-authored', () => {
  assert.ok(fs.existsSync(STATE_PATH), 'state.js missing — regenerate with aegis-state.cjs --out');
  const s = fs.readFileSync(STATE_PATH, 'utf8');
  assert.ok(/Generated by builder-control\/aegis-state\.cjs/.test(s), 'state.js lacks its generator header');
  assert.ok(/do not edit by hand/i.test(s));
  const json = JSON.parse(s.slice(s.indexOf('{'), s.lastIndexOf('}') + 1));
  assert.deepStrictEqual(json.contract.absences, ['UNAVAILABLE', 'STALE', 'UNVERIFIED']);
});

test('state.js loads BEFORE the renderer, or the renderer would always see nothing', () => {
  // Search the comment-stripped source. The file's own header comment mentions
  // window.AEGIS_STATE while explaining the rule, and matching that prose
  // instead of the executable read made this test fail on correct code.
  const stateTag = code.indexOf('<script src="state.js">');
  const renderer = code.indexOf('var S = window.AEGIS_STATE');
  assert.ok(stateTag !== -1, 'state.js is never loaded');
  assert.ok(renderer !== -1, 'the renderer no longer reads window.AEGIS_STATE');
  assert.ok(stateTag < renderer,
    `state.js (@${stateTag}) must load before the renderer reads it (@${renderer})`);
});

// ── no fabricated values ────────────────────────────────────────────────────
test('no hardcoded status word appears in the markup', () => {
  const body = html.slice(html.indexOf('<body'));
  const markup = body.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<!--[\s\S]*?-->/g, '');
  for (const word of ['PASS', 'HEALTHY', 'VERIFIED', 'COMPLETE']) {
    assert.ok(!new RegExp('>\\s*' + word).test(markup),
      `the literal "${word}" appears in static markup — every status must come from state`);
  }
});

test('no fabricated progress, percentage, uptime or KPI vocabulary', () => {
  for (const banned of ['percentComplete', 'progressPercent', 'uptime', 'Math.random', 'toFixed(0) + \'%\'']) {
    assert.ok(!code.includes(banned), `"${banned}" found — the slice must not synthesise numbers`);
  }
  assert.ok(!/\b\d{1,3}%\s*<\//.test(html), 'a literal percentage is rendered in markup');
});

// ── the three honest absences are all reachable ─────────────────────────────
test('UNAVAILABLE, STALE and UNVERIFIED each have a rendering', () => {
  for (const s of ['UNAVAILABLE', 'STALE', 'UNVERIFIED']) {
    assert.ok(code.includes(s), `${s} has no rendering path`);
    assert.ok(new RegExp('\\.s-' + s + '\\b').test(code) || new RegExp('s-\\$\\{?').test(code),
      `${s} has no state style`);
  }
  assert.ok(/UNAVAILABLE — no AEGIS state is loaded/.test(code),
    'the no-state failure path must be explicit, not an empty page');
});

test('status is never colour-only — every chip carries a glyph and a label', () => {
  assert.ok(/GLYPH\s*=/.test(code), 'no glyph map');
  assert.ok(/c\.appendChild\(el\('span',null,state\)\)/.test(code),
    'the chip must append the state name as text, not rely on colour');
});

// ── 2D is the product ───────────────────────────────────────────────────────
test('no WebGL, no 3D library, no canvas — 2D is authoritative, not a fallback', () => {
  for (const banned of ['webgl', 'three.js', 'THREE.', '<canvas', 'getContext(']) {
    assert.ok(!code.toLowerCase().includes(banned.toLowerCase()),
      `"${banned}" found — the V1 slice must be fully operational without any 3D layer`);
  }
});

// Amended for the switchboard (PKT-20260825-SWITCHBOARD-FOUNDATION): the page
// is now an authenticated control surface, not a file:// static view, and
// legitimately calls same-origin /api/* over fetch()/EventSource. The
// invariant that must never regress is "no CDN, no remote font, no absolute
// URL" — every request stays same-origin and relative.
test('zero external requests: no CDN, no remote font, no absolute URL', () => {
  assert.ok(!/https?:\/\//.test(code.replace(/xmlns="[^"]*"/g, '')),
    'an absolute URL is referenced — this must remain a same-origin control surface');
  for (const m of code.matchAll(/\bfetch\s*\(\s*(['"])([^'"]*)\1/g)) {
    assert.ok(m[2].startsWith('/'), `fetch() must target a same-origin relative path, got: ${m[2]}`);
  }
  for (const m of code.matchAll(/new EventSource\(\s*(['"])([^'"]*)\1/g)) {
    assert.ok(m[2].startsWith('/'), `EventSource must target a same-origin relative path, got: ${m[2]}`);
  }
});

// ── accessibility invariants ────────────────────────────────────────────────
test('keyboard and assistive-tech affordances are present', () => {
  assert.ok(/aria-live="polite"/.test(html), 'no live region');
  assert.ok(/aria-label/.test(code), 'stages carry no accessible label');
  assert.ok(/:focus-visible/.test(code), 'no visible focus style');
  assert.ok(/Escape/.test(code), 'no keyboard dismiss');
  assert.ok(/ArrowDown/.test(code) && /ArrowUp/.test(code), 'no arrow-key traversal along the path');
  assert.ok(/class="sr"[^>]*href="#topology"/.test(html), 'no skip link');
});

test('every state colour token clears 3:1 on the panel background', () => {
  const vars = {};
  const rootBlock = code.slice(code.indexOf(':root{'), code.indexOf('}', code.indexOf(':root{')));
  for (const m of rootBlock.matchAll(/(--[\w-]+):\s*(#[0-9a-fA-F]{6})/g)) vars[m[1]] = m[2];
  const lum = (h) => {
    const c = h.slice(1).match(/../g).map((x) => {
      const v = parseInt(x, 16) / 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
  };
  const ratio = (a, b) => { const l1 = lum(a), l2 = lum(b); const hi = Math.max(l1, l2), lo = Math.min(l1, l2); return (hi + 0.05) / (lo + 0.05); };
  const bg = vars['--bg-1'];
  assert.ok(bg, 'no --bg-1 token');
  for (const t of ['--pass', '--active', '--warn', '--fail', '--blocked', '--stale', '--unknown', '--text-0', '--text-1']) {
    assert.ok(vars[t], `token ${t} missing`);
    const r = ratio(vars[t], bg);
    assert.ok(r >= 3, `${t} (${vars[t]}) is ${r.toFixed(2)}:1 on ${bg} — below the 3:1 this design requires`);
  }
});

// ── VISUAL INTEGRATION RED PROOFS ─────────────────────────────────────────
test('RED: the page renders ELEVEN steps and numbers them', () => {
  const state = JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')
    .replace(/^[\s\S]*?window\.AEGIS_STATE = /, '').replace(/;\s*$/, ''));
  assert.strictEqual(state.engineering.stages.length, 11,
    'the projection the page reads must carry exactly 11 steps');
  assert.ok(/st\.step/.test(htmlSrc()), 'the page must render the contract step number');
  assert.ok(/stepno/.test(htmlSrc()), 'step numbers need their own style hook');
});

test('RED: exactly ONE topology list exists — no duplicated view', () => {
  // A duplicated topology is the classic full-page-duplication bug: two lists
  // render, both look plausible, and they drift apart silently.
  const listIds = (htmlSrc().match(/id="stages"/g) || []).length;
  assert.strictEqual(listIds, 1, `expected one stage list, found ${listIds}`);
  const topo = (htmlSrc().match(/id="topology"/g) || []).length;
  assert.strictEqual(topo, 1, `expected one topology section, found ${topo}`);
  const bodies = (htmlSrc().match(/<body/g) || []).length;
  assert.ok(bodies <= 1, 'more than one body element would duplicate the whole page');
});

test('RED: the page renders SPEND and never a bare zero for unrecorded cost', () => {
  assert.ok(/id="cost"/.test(htmlSrc()), 'a spend panel must exist');
  assert.ok(/S\.cost/.test(htmlSrc()), 'the page must read the cost projection');
  assert.ok(/UNRECORDED/.test(htmlSrc()), 'the page must be able to say UNRECORDED');
  assert.ok(/AT LEAST|totalUsd/.test(htmlSrc()), 'the headline total must be able to say AT LEAST');
  // A hardcoded currency figure would be a fabricated KPI.
  const hardcoded = htmlSrc().match(/USD\s+\d+\.\d+/g) || [];
  assert.deepStrictEqual(hardcoded, [], `hardcoded currency in the page: ${hardcoded.join(', ')}`);
});

test('RED: no external requests, still', () => {
  const ext = htmlSrc().match(/(?:src|href)\s*=\s*["']https?:\/\//g) || [];
  assert.deepStrictEqual(ext, [], 'the page must make zero external requests');
});

test('RED: responsive rules cover narrow and large widths', () => {
  const queries = htmlSrc().match(/@media[^{]+/g) || [];
  assert.ok(queries.length >= 2, `expected responsive breakpoints, found ${queries.length}`);
  assert.ok(/prefers-reduced-motion/.test(htmlSrc()), 'reduced motion must be honoured');
});

test('RED: every rendered stage carries provenance and a reason', () => {
  const state = JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')
    .replace(/^[\s\S]*?window\.AEGIS_STATE = /, '').replace(/;\s*$/, ''));
  for (const st of state.engineering.stages) {
    assert.ok(st.evidence, `step ${st.step} has no evidence source`);
    assert.ok(st.reason, `step ${st.step} has no reason`);
    assert.ok(!/^PASS$/.test(st.state) || st.reason.length > 10,
      `step ${st.step} claims PASS with no substantive reason`);
  }
});

// ── CORRECTION CYCLE 1 (PKT-20260825-GOVERNANCE-TRUTH) — founder readability ─
test('a primary founder summary exists with what/now/why/next, ahead of the raw state', () => {
  const founderIdx = htmlSrc().indexOf('id="founder-summary"');
  const rawIdx = htmlSrc().indexOf('id="raw-state"');
  assert.ok(founderIdx !== -1, 'no founder-summary section exists');
  assert.ok(rawIdx !== -1, 'no raw-state details wrapper exists');
  assert.ok(founderIdx < rawIdx, 'the founder summary must read before the raw machine state, not after');
  assert.ok(/What was requested/.test(code), 'no "what was requested" field');
  assert.ok(/What is happening now/.test(code), 'no "what is happening now" field');
  assert.ok(/Why blocked/.test(code), 'no "why blocked" field');
  assert.ok(/Next action/.test(code), 'no "next action" field');
});

test('the raw machine state (topology, connectors, knowledge, reviewers) sits inside a <details>, collapsed by default', () => {
  const html = htmlSrc();
  const detailsOpen = html.indexOf('<details id="raw-state">');
  const detailsClose = html.indexOf('</details>', detailsOpen);
  assert.ok(detailsOpen !== -1 && detailsClose !== -1, 'raw-state <details> not found');
  assert.ok(!/<details[^>]*id="raw-state"[^>]*\bopen\b/.test(html), 'raw-state must not force itself open — it is advanced detail, not the primary view');
  const inner = html.slice(detailsOpen, detailsClose);
  for (const id of ['id="topology"', 'id="conn-h"', 'id="know-h"', 'id="rev-h"']) {
    assert.ok(inner.includes(id), `${id} must be inside the raw-state details, not a duplicate copy outside it`);
  }
});

test('previous runs are collapsed into a <details> inside the founder summary', () => {
  assert.ok(/Previous runs/.test(code), 'no collapsed "previous runs" affordance');
});

test('connector usage is driven by lastUsedByRun, and the two untruthful phrases are gone', () => {
  // These two phrases were the defect (CONFIRMED FINDING #10), not the fix:
  // "Not used for this run" asserted a negative the projector never proved, and
  // "Consulted for this run" claimed a current-run match that was never checked.
  assert.ok(!/Not used for this run/.test(code), 'the unprovable negative "Not used for this run" is back in the page');
  assert.ok(!/Consulted for this run/.test(code), 'the unchecked claim "Consulted for this run" is back in the page');
  assert.ok(/usageMessage\s*\(/.test(code), 'no usageMessage() renderer for connector usage');
  const fn = code.slice(code.indexOf('function usageMessage'), code.indexOf('function usageMessage') + 2000);
  assert.ok(/used\.runId\s*===\s*curRunId/.test(fn),
    '"for this run" must be gated on an exact runId match, not on the presence of a usage record');
  assert.ok(/c\.lastUsedByRun/.test(code), 'connector usage text is not reading lastUsedByRun');
});

test('the inspector renders authentication, lastVerified and lastUsedByRun as three separate lines', () => {
  assert.ok(/data\.authentication/.test(code), 'inspector does not render the authentication fact');
  assert.ok(/data\.lastVerified/.test(code), 'inspector does not render the lastVerified fact');
  assert.ok(/data\.lastUsedByRun/.test(code), 'inspector does not render the lastUsedByRun fact');
});

test('the Pause action is disabled, not merely titled — there is no active build process to suspend', () => {
  const idx = code.indexOf("el('button', 'action', 'Pause')");
  assert.ok(idx !== -1, 'no Pause button found');
  const nearby = code.slice(idx, idx + 400);
  assert.ok(/pauseBtn\.disabled\s*=\s*true/.test(nearby), 'Pause must be disabled — it is unavailable for every run today');
});

test('every rendered field still goes through textContent/DOM APIs — no innerHTML of untrusted data', () => {
  assert.ok(!/\.innerHTML\s*=/.test(code), 'innerHTML assignment found — every field here is untrusted input from state or the API');
});


// ── DOM harness: render the REAL page source, not a copy of it ─────────────
// jsdom is not a dependency here and will not become one for a governance
// dashboard, so this is a deliberately small DOM: enough of createElement /
// appendChild / textContent / getElementById for the page's own renderers to
// run untouched, and nothing else. It executes the <script> blocks EXTRACTED
// FROM index.html, so a proof that passes here passed against the file that
// ships. If the page starts using a DOM API this shim lacks, these tests throw
// rather than silently assert against a stub.
const vm = require('vm');

function makeNode(tag) {
  const node = {
    tagName: String(tag || '').toUpperCase(),
    className: '',
    children: [],
    attrs: {},
    _text: '',
    style: {},
    dataset: {},
    appendChild(c) { this.children.push(c); return c; },
    insertBefore(c, ref) {
      const i = this.children.indexOf(ref);
      if (i === -1) this.children.push(c); else this.children.splice(i, 0, c);
      return c;
    },
    removeChild(c) {
      const i = this.children.indexOf(c);
      if (i !== -1) this.children.splice(i, 1);
      return c;
    },
    setAttribute(k, v) { this.attrs[k] = String(v); },
    getAttribute(k) { return Object.prototype.hasOwnProperty.call(this.attrs, k) ? this.attrs[k] : null; },
    removeAttribute(k) { delete this.attrs[k]; },
    addEventListener(type, fn) { (this._listeners[type] = this._listeners[type] || []).push(fn); },
    querySelectorAll() { return []; },
    focus() {},
    _listeners: {},
    classList: {
      contains(c) { return String(node.className).split(/\s+/).includes(c); },
    },
  };
  Object.defineProperty(node, 'textContent', {
    get() {
      if (!node.children.length) return node._text;
      return node._text + node.children.map((c) => c.textContent).join('');
    },
    set(v) { node.children.length = 0; node._text = String(v); },
  });
  Object.defineProperty(node, 'firstElementChild', { get() { return node.children[0] || null; } });
  Object.defineProperty(node, 'firstChild', { get() { return node.children[0] || null; } });
  Object.defineProperty(node, 'lastChild', { get() { return node.children[node.children.length - 1] || null; } });
  return node;
}

// Depth-first search for a node carrying an attribute, so a test can ask for
// "the connector usage line" without knowing the page's element structure.
function findByAttr(root, attr, out = []) {
  if (root.attrs && root.attrs[attr] !== undefined) out.push(root);
  (root.children || []).forEach((c) => findByAttr(c, attr, out));
  return out;
}

function pageScripts() {
  // Only inline scripts. <script src="state.js"> is the state file, which each
  // fixture supplies directly as window.AEGIS_STATE.
  const out = [];
  const re = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;
  let m;
  while ((m = re.exec(htmlSrc())) !== null) out.push(m[1]);
  assert.ok(out.length >= 2, 'expected the renderer and the switchboard script blocks in the page');
  return out;
}

// Boot the page against a fixture. Returns the sandbox plus the captured SSE
// listeners, so a test can push a status event exactly as the server would.
function bootPage(state, opts = {}) {
  const byId = new Map();
  const document = {
    getElementById(id) {
      if (!byId.has(id)) { const n = makeNode('div'); n.attrs.id = id; byId.set(id, n); }
      return byId.get(id);
    },
    createElement: (t) => makeNode(t),
    createTextNode(t) { const n = makeNode('#text'); n._text = String(t); return n; },
    addEventListener() {},
    body: makeNode('body'),
  };
  const sse = { listeners: {}, opened: false };
  const sandbox = {
    document,
    console: { log() {}, error() {} },
    Date,
    JSON,
    Math,
    Object,
    Array,
    String,
    Number,
    Boolean,
    RegExp,
    Error,
    Promise,
    fetch: opts.fetch || (async () => ({ ok: true, json: async () => opts.status || {} })),
    EventSource: function () {
      sse.opened = true;
      return {
        addEventListener(type, fn) { (sse.listeners[type] = sse.listeners[type] || []).push(fn); },
        set onerror(_f) {}, set onopen(_f) {},
      };
    },
  };
  sandbox.window = sandbox;
  sandbox.window.AEGIS_STATE = state;
  sandbox.window.matchMedia = () => ({ matches: false });
  vm.createContext(sandbox);
  for (const src of pageScripts()) vm.runInContext(src, sandbox, { filename: 'dashboard/index.html' });
  return { sandbox, document, byId, sse, text: (id) => document.getElementById(id).textContent };
}

// Fixture builders — deliberately explicit, so what each proof assumes is
// visible in the proof rather than buried in a shared blob.
function fixtureState(over) {
  const base = {
    generatedAt: '2026-08-25T23:00:00.000Z',
    contract: { absences: ['UNAVAILABLE', 'STALE', 'UNVERIFIED'] },
    engineering: {
      state: 'OK', verdict: 'BLOCKED', lane: 'FULL', highRisk: true,
      laneWhy: ['a high-risk signal is present'],
      riskReasons: ['touches a protected path'],
      subjectSha256: 'aaaaaaaaaaaabbbbbbbbbbbbcccccccccccc',
      subjectPaths: ['builder-control/dashboard/index.html'],
      problems: [{ rule: 'ENGOS-REVIEW-MISSING', detail: 'grok is required and has no review bound to this subject.' }],
      reviewerCompleteness: { complete: false, rows: [] },
      stages: [], source: 'builder-control/engineering-os.cjs',
    },
    integration: { connectors: { state: 'OK', connectors: [] } },
    knowledge: { state: 'OK', records: [] },
    reviewers: { state: 'OK', reviewers: [] },
    cost: { state: 'UNAVAILABLE', reason: 'no transcripts' },
    runs: { state: 'OK', runs: [], current: { state: 'UNAVAILABLE', reason: 'no run records exist yet, so no run is current.' } },
    events: { state: 'OK', events: [] },
  };
  return Object.assign(base, over || {});
}

function connectorFixture(lastUsedByRun) {
  return {
    connectorId: 'c1', label: 'Test connector', provider: 'test', plane: 'INTEGRATION',
    executionPath: 'mcp', authStatus: 'AUTHENTICATED', health: 'HEALTHY',
    staleness: { state: 'FRESH' }, capabilities: [], declaredNotSupported: [],
    failureCount: 0, riskLevel: 'LOW', legacy: false, source: 'builder-control/connector-registry.json',
    lastUsedByRun,
  };
}

// ── FINDING #10 RED PROOF: four evidence states, four different sentences ──
test('RED: connector usage renders four distinct, truthful messages from real DOM output', () => {
  const cases = [
    { name: 'absent evidence',
      used: { state: 'UNAVAILABLE', plain: 'x' },
      bound: 'RUN-A',
      expectState: 'UNAVAILABLE',
      must: [/UNAVAILABLE/, /no record exists/i],
      mustNot: [/\bUsed by this run\b/, /Last used by run/] },
    { name: 'unconfirmed claim',
      used: { state: 'UNVERIFIED', claim: { runId: 'RUN-CLAIM' } },
      bound: 'RUN-A',
      expectState: 'UNVERIFIED',
      must: [/UNVERIFIED/, /RUN-CLAIM/, /claim/i],
      mustNot: [/\bUsed by this run\b/] },
    { name: 'confirmed historical use by another run',
      used: { state: 'USED', runId: 'RUN-OLD', observedAt: '2026-08-01T00:00:00.000Z', ledgerConfirmed: true },
      bound: 'RUN-A',
      expectState: 'USED_HISTORICAL',
      must: [/Last used by run RUN-OLD/, /not the current run/],
      mustNot: [/\bUsed by this run\b/] },
    { name: 'confirmed use by the exact current run',
      used: { state: 'USED', runId: 'RUN-A', observedAt: '2026-08-25T00:00:00.000Z', ledgerConfirmed: true },
      bound: 'RUN-A',
      expectState: 'USED_CURRENT',
      must: [/Used by this run \(RUN-A\)/],
      mustNot: [/Last used by run/] },
  ];
  const seen = new Set();
  for (const c of cases) {
    const state = fixtureState({
      integration: { connectors: { state: 'OK', connectors: [connectorFixture(c.used)] } },
      runs: { state: 'OK', runs: [{ runId: c.bound, state: 'BUILT', objective: 'o', updatedAt: '2026-08-25T00:00:00.000Z' }],
        current: { state: 'BOUND', runId: c.bound, updatedAt: '2026-08-25T00:00:00.000Z', packetId: null, subjectSha256: null, reason: 'r' } },
    });
    const page = bootPage(state);
    const lines = findByAttr(page.document.getElementById('connectors'), 'data-usage-state');
    assert.strictEqual(lines.length, 1, `${c.name}: expected exactly one usage line, got ${lines.length}`);
    const line = lines[0];
    assert.strictEqual(line.attrs['data-usage-state'], c.expectState, `${c.name}: wrong usage state`);
    for (const re of c.must) assert.ok(re.test(line.textContent), `${c.name}: rendered text missing ${re} — got: ${line.textContent}`);
    for (const re of c.mustNot) assert.ok(!re.test(line.textContent), `${c.name}: rendered text wrongly asserts ${re} — got: ${line.textContent}`);
    assert.ok(!seen.has(line.textContent), `${c.name}: this message is identical to another state's message`);
    seen.add(line.textContent);
  }
  assert.strictEqual(seen.size, 4, 'the four evidence states must produce four different sentences');
});

test('RED: a confirmed use is never called "this run" when no run is bound', () => {
  const state = fixtureState({
    integration: { connectors: { state: 'OK', connectors: [connectorFixture(
      { state: 'USED', runId: 'RUN-OLD', observedAt: '2026-08-01T00:00:00.000Z', ledgerConfirmed: true })] } },
    runs: { state: 'OK', runs: [], current: { state: 'UNAVAILABLE', reason: 'no run records exist yet, so no run is current.' } },
  });
  const page = bootPage(state);
  const line = findByAttr(page.document.getElementById('connectors'), 'data-usage-state')[0];
  assert.strictEqual(line.attrs['data-usage-state'], 'USED_HISTORICAL');
  assert.ok(/Last used by run RUN-OLD/.test(line.textContent));
  assert.ok(/No current run is bound/.test(line.textContent),
    'with no binding the page must say so rather than imply the use belongs to the current run');
});

// ── FINDING #7 RED PROOFS: binding, not array position ────────────────────
test('RED: the current run is selected by timestamp, not by array position', () => {
  // Deliberately out of order: the NEWEST run is FIRST in the array, and the
  // run ids do not sort in time order either. Old behaviour (last element)
  // would show the stale objective.
  const runs = [
    { runId: 'RUN-20260826-aaaa', state: 'BUILT', objective: 'THE NEW OBJECTIVE', updatedAt: '2026-08-26T10:00:00.000Z', packetId: 'builder-control/packets/P-NEW.json' },
    { runId: 'RUN-20260825-zzzz', state: 'BUILT', objective: 'THE STALE OBJECTIVE', updatedAt: '2026-08-25T10:00:00.000Z', packetId: 'builder-control/packets/P-OLD.json' },
  ];
  const state = fixtureState({ runs: { state: 'OK', runs,
    current: { state: 'BOUND', runId: 'RUN-20260826-aaaa', updatedAt: '2026-08-26T10:00:00.000Z',
      packetId: 'builder-control/packets/P-NEW.json', subjectSha256: 'aaaaaaaaaaaabbbb', objective: 'THE NEW OBJECTIVE',
      reason: 'Bound to RUN-20260826-aaaa, whose own record was last written 2026-08-26T10:00:00.000Z.' } } });
  const body = bootPage(state).text('founder-body');
  assert.ok(/THE NEW OBJECTIVE/.test(body), 'the bound run objective is not rendered');
  assert.ok(!/What was requested: THE STALE OBJECTIVE/.test(body), 'a stale objective is being presented as current');
  // All four coordinates must be stated, not just the run id.
  assert.ok(/RUN-20260826-aaaa/.test(body), 'run id missing');
  assert.ok(/2026-08-26T10:00:00.000Z/.test(body), 'authoritative timestamp missing');
  assert.ok(/P-NEW\.json/.test(body), 'packet id missing');
  assert.ok(/aaaaaaaaaaaa/.test(body), 'subject hash missing');
});

test('RED: with no authoritative binding the summary renders UNAVAILABLE, not the last run in the list', () => {
  const state = fixtureState({ runs: { state: 'OK',
    runs: [{ runId: 'RUN-UNDATED', state: 'BUILT', objective: 'UNDATED OBJECTIVE', updatedAt: null }],
    current: { state: 'UNAVAILABLE', runId: null,
      reason: '1 run record(s) exist but none carries a parseable updatedAt timestamp, so which one is current cannot be established.' } } });
  const body = bootPage(state).text('founder-body');
  assert.ok(/UNAVAILABLE/.test(body), 'an unbound summary must say UNAVAILABLE');
  assert.ok(!/What was requested: UNDATED OBJECTIVE/.test(body),
    'an undated run must not be promoted to "current" — selecting by list position is the defect');
  assert.ok(/none carries a parseable updatedAt/.test(body), 'the reason the binding failed must be shown');
});

test('RED: the founder summary states the risk tier, its reasons, and reviewer coverage in plain English', () => {
  const state = fixtureState({ engineering: Object.assign(fixtureState().engineering, {
    reviewerCompleteness: { complete: false, rows: [
      { reviewer: 'codex', job: 'correctness reviewer', required: 'REQUIRED', executed: 'EXECUTED',
        disposition: 'REJECT', score: '1/2 subject path(s) covered',
        coveredPaths: ['a.cjs'], missingPaths: ['b.cjs'], stalePaths: ['gone.cjs'], reason: 'r' },
      { reviewer: 'grok', job: 'adversarial reviewer', required: 'REQUIRED', executed: 'MISSING',
        disposition: null, score: 'UNAVAILABLE', coveredPaths: [], missingPaths: ['a.cjs', 'b.cjs'], stalePaths: [], reason: 'r' },
    ] } }) });
  const body = bootPage(state).text('founder-body');
  assert.ok(/Risk tier: FULL \(high-risk\)/.test(body), 'the risk tier and high-risk flag are not stated');
  assert.ok(/a high-risk signal is present/.test(body), 'the classifier reason for the tier is not shown');
  assert.ok(/touches a protected path/.test(body), 'the risk reason is not shown');
  assert.ok(/codex/.test(body) && /grok/.test(body), 'reviewer names are not shown');
  assert.ok(/rejected it/.test(body), 'the reviewer disposition is not in plain English');
  assert.ok(/1\/2 subject path\(s\) covered/.test(body), 'the reviewer score is not shown');
  assert.ok(/has not reviewed this change/.test(body), 'a missing required review is not stated plainly');
  // covered / not read / no-longer-part-of-this-change, all three
  assert.ok(/Read: a\.cjs/.test(body), 'covered paths missing');
  assert.ok(/Not read: b\.cjs/.test(body), 'missing paths missing');
  assert.ok(/gone\.cjs/.test(body), 'stale paths missing');
});

test('RED: an absent reviewer table renders UNAVAILABLE, never "complete"', () => {
  const eng = Object.assign(fixtureState().engineering, { reviewerCompleteness: null });
  const body = bootPage(fixtureState({ engineering: eng })).text('founder-body');
  assert.ok(/reviewer coverage is unknown/.test(body), 'a missing reviewer table must read as unknown coverage');
  assert.ok(!/Every required reviewer read every changed file/.test(body), 'unknown coverage rendered as complete');
});

// ── FINDING #2: the exact coverage sentence has to reach the screen ────────
// The gate computes one founder-readable sentence naming which reviewer fell
// short, how, and what to re-run. Hosting already carries it as
// engineering.reviewerCompleteness.completeReason. These proofs hold that the
// panel BINDS that field rather than paraphrasing it, and that it stays text.
function rcFixture(completeReason, over) {
  return fixtureState({ engineering: Object.assign(fixtureState().engineering, {
    reviewerCompleteness: Object.assign({
      complete: false,
      completeReason,
      rows: [
        { reviewer: 'codex', job: 'correctness reviewer', required: 'REQUIRED', executed: 'EXECUTED',
          disposition: 'APPROVE', score: '1/2 subject path(s) covered',
          coveredPaths: ['a.cjs'], missingPaths: ['b.cjs'], stalePaths: [], reason: 'r' },
      ],
    }, over || {}) }) });
}

// Every element the page built, so a proof can ask what was CREATED rather
// than only what the concatenated text reads like.
function allNodes(root, out = []) {
  out.push(root);
  (root.children || []).forEach((c) => allNodes(c, out));
  return out;
}

test('RED: incomplete coverage renders the gate\'s exact completeness sentence, not just a yes/no', () => {
  const reason = 'Review coverage is INCOMPLETE: codex read only part of the change. ' +
    'Re-run the reviewer(s) named above against this exact change.';
  const body = bootPage(rcFixture(reason)).text('founder-body');
  assert.ok(/Not every required reviewer has read every changed file/.test(body),
    'the coverage headline is gone');
  assert.ok(body.includes(reason),
    'engineering.reviewerCompleteness.completeReason is not bound to the panel — the founder is told THAT coverage is short but never which reviewer, how, or what to re-run');
});

test('RED: complete coverage renders its own exact sentence too, so "complete" is never unexplained', () => {
  const reason = 'Every required reviewer (codex and grok) reviewed this exact change and read all ' +
    '2 changed file(s), and no reviewer claims a file outside it.';
  const body = bootPage(rcFixture(reason, { complete: true })).text('founder-body');
  assert.ok(body.includes(reason), 'a complete verdict is asserted with no evidence sentence behind it');
});

test('RED: a completeness sentence the gate never recorded reads as UNAVAILABLE, never as blank or complete', () => {
  const body = bootPage(rcFixture(null)).text('founder-body');
  assert.ok(/no explanation for this coverage verdict/.test(body),
    'an absent completeReason silently vanishes — absence must be stated, not rendered as nothing');
  assert.ok(/UNAVAILABLE/.test(body), 'the absence is not labelled with a contract absence word');
  assert.ok(!/Every required reviewer read every changed file/.test(body),
    'a missing reason rendered as complete coverage');
});

test('RED: the completeness sentence is text — markup in a reviewer name or path cannot become DOM', () => {
  const hostile = 'Review coverage is INCOMPLETE: <img src=x onerror="alert(1)"> read only part of ' +
    '<script>alert(2)</script> the change. Re-run the reviewer(s) named above against this exact change.';
  const page = bootPage(rcFixture(hostile));
  const host = page.document.getElementById('founder-body');
  assert.ok(page.text('founder-body').includes(hostile),
    'the sentence was mangled or dropped instead of being shown verbatim as text');
  const tags = allNodes(host).map((n) => n.tagName);
  assert.ok(!tags.includes('SCRIPT') && !tags.includes('IMG'),
    `markup inside the sentence was parsed into elements: ${tags.join(',')}`);
  // The whole sentence must live in ONE text-bearing node, which is what
  // textContent assignment produces; parsing would have split it into children.
  const carrier = allNodes(host).filter((n) => n._text === hostile);
  assert.strictEqual(carrier.length, 1,
    'the sentence is not carried by a single textContent assignment — some other, unsafe write path is in use');
});

test('RED: the spend panel shows CAD only from dated FX evidence, and UNAVAILABLE without it', () => {
  const noFx = fixtureState({ cost: { state: 'OK', recordedUsdDisplay: 2.46, totalUsd: 'AT LEAST 2.46',
    recordedRuns: 3, unrecordedRuns: 1, caveat: null, byReviewer: { codex: { recordedUsd: 2.46, unrecordedRuns: 1 } },
    cad: { state: 'UNAVAILABLE', reason: 'no canonical FX evidence exists at builder-control/fx-canon.json' },
    source: 'builder-control/review-raw' } });
  const bodyNoFx = bootPage(noFx).text('cost');
  assert.ok(/CAD UNAVAILABLE/.test(bodyNoFx), 'with no rate evidence the headline must read CAD UNAVAILABLE');
  assert.ok(/no canonical FX evidence/.test(bodyNoFx), 'the reason CAD is unavailable must be shown');
  assert.ok(/USD AT LEAST 2\.46/.test(bodyNoFx), 'the USD audit value must survive');

  const withFx = fixtureState({ cost: Object.assign({}, noFx.cost, {
    cad: { state: 'OK', rate: 1.37, asOf: '2026-08-24', ageDays: 1, fxSource: 'Bank of Canada daily rate',
      source: 'builder-control/fx-canon.json', plain: '1 USD = 1.37 CAD, observed 2026-08-24 (Bank of Canada daily rate).',
      recordedCad: 3.38, totalCad: 'AT LEAST 3.38', byReviewerCad: { codex: { recordedCad: 3.38, unrecordedRuns: 1 } } } }) });
  const bodyFx = bootPage(withFx).text('cost');
  assert.ok(/CAD AT LEAST 3\.38/.test(bodyFx), 'the CAD headline is not rendered from the evidence');
  assert.ok(/1 USD = 1\.37 CAD/.test(bodyFx), 'the rate itself must be shown');
  assert.ok(/2026-08-24/.test(bodyFx), 'the rate date must be shown');
  assert.ok(/Bank of Canada daily rate/.test(bodyFx), 'the rate source must be shown');
  assert.ok(/builder-control\/fx-canon\.json/.test(bodyFx), 'the rate evidence file must be cited');
  assert.ok(/USD AT LEAST 2\.46/.test(bodyFx), 'the USD audit value must be preserved alongside CAD');
});

test('no FX rate is hardcoded anywhere in the page — a rate may only arrive as evidence', () => {
  assert.ok(!/\b1\.[23]\d\b/.test(code.replace(/--[\w-]+:[^;]*;/g, '')),
    'a literal exchange-rate-shaped constant appears in the page');
  assert.ok(!/exchangerate|openexchange|fixer\.io|api\.frankfurter/i.test(code),
    'the page must never fetch a live FX rate');
});

// ── FINDING #7 RED PROOF: the summary must REPAINT from the live stream ────
// The panel used to render once from the generated snapshot and never again,
// so a founder watching the page saw an old objective and an old verdict
// presented as current. This drives the page exactly as the server does: an
// authenticated /api/status bootstrap, then a pushed `status` SSE event.
async function asyncTests() {
  await atest('RED: an SSE status push repaints the founder summary with the newly bound run', async () => {
    const state = fixtureState({ runs: { state: 'OK',
      runs: [{ runId: 'RUN-OLD', state: 'BUILT', objective: 'OLD OBJECTIVE', updatedAt: '2026-08-25T10:00:00.000Z' }],
      current: { state: 'BOUND', runId: 'RUN-OLD', updatedAt: '2026-08-25T10:00:00.000Z', packetId: null,
        subjectSha256: 'old000000000aaaa', objective: 'OLD OBJECTIVE', reason: 'bound to RUN-OLD' } } });

    // The bootstrap GET returns the SAME state the page was generated with, so
    // any change below can only have come from the pushed event.
    const bootstrapStatus = {
      generatedAt: '2026-08-25T23:00:00.000Z',
      engineering: { state: 'OK', verdict: 'BLOCKED', lane: 'FULL', highRisk: true, laneWhy: [], riskReasons: [],
        subjectSha256: 'old000000000aaaa', problems: [], reviewerCompleteness: null, stages: [] },
      runs: [{ runId: 'RUN-OLD', state: 'BUILT', objective: 'OLD OBJECTIVE', updatedAt: '2026-08-25T10:00:00.000Z' }],
      runsBinding: { state: 'BOUND', runId: 'RUN-OLD', updatedAt: '2026-08-25T10:00:00.000Z', packetId: null,
        subjectSha256: 'old000000000aaaa', objective: 'OLD OBJECTIVE', reason: 'bound to RUN-OLD' },
      cost: { state: 'UNAVAILABLE', reason: 'none' }, events: [], integration: { connectors: [] }, reviewers: [],
      knowledge: { state: 'OK', conflicts: 0 },
    };
    const page = bootPage(state, { status: bootstrapStatus });
    // Let the bootstrap's awaits settle before pushing.
    for (let i = 0; i < 10; i++) await Promise.resolve();
    assert.ok(page.sse.listeners.status && page.sse.listeners.status.length,
      'the page never subscribed to the status stream');
    assert.ok(/OLD OBJECTIVE/.test(page.text('founder-body')), 'precondition: the old run should be showing');

    const pushed = JSON.parse(JSON.stringify(bootstrapStatus));
    pushed.generatedAt = '2026-08-26T10:00:01.000Z';
    pushed.engineering.verdict = 'READY_FOR_PR';
    pushed.engineering.subjectSha256 = 'new999999999bbbb';
    pushed.runs.unshift({ runId: 'RUN-NEW', state: 'BUILT', objective: 'NEW OBJECTIVE',
      updatedAt: '2026-08-26T10:00:00.000Z', packetId: 'builder-control/packets/P-NEW.json' });
    pushed.runsBinding = { state: 'BOUND', runId: 'RUN-NEW', updatedAt: '2026-08-26T10:00:00.000Z',
      packetId: 'builder-control/packets/P-NEW.json', subjectSha256: 'new999999999bbbb', objective: 'NEW OBJECTIVE',
      reason: 'bound to RUN-NEW' };
    page.sse.listeners.status.forEach((fn) => fn({ data: JSON.stringify(pushed) }));

    const after = page.text('founder-body');
    assert.ok(/NEW OBJECTIVE/.test(after), 'the pushed run did not replace the summary');
    assert.ok(!/What was requested: OLD OBJECTIVE/.test(after), 'the stale objective survived a live push');
    assert.ok(/RUN-NEW/.test(after), 'the newly bound run id is not shown');
    assert.ok(/new999999999/.test(after), 'the summary is not bound to the pushed subject hash');
    assert.ok(/P-NEW\.json/.test(after), 'the pushed packet id is not shown');
    assert.ok(/Ready to open a pull request/.test(after), 'the pushed verdict did not repaint');
    // The whole point of the binding: the same subject hash governs both.
    assert.ok(!/old000000000/.test(after), 'the old subject hash is still on screen after the repaint');
  });

  await atest('RED: a malformed live push never blanks or half-paints the summary', async () => {
    const state = fixtureState({ runs: { state: 'OK',
      runs: [{ runId: 'RUN-OLD', state: 'BUILT', objective: 'OLD OBJECTIVE', updatedAt: '2026-08-25T10:00:00.000Z' }],
      current: { state: 'BOUND', runId: 'RUN-OLD', updatedAt: '2026-08-25T10:00:00.000Z', packetId: null,
        subjectSha256: 'old000000000aaaa', objective: 'OLD OBJECTIVE', reason: 'bound to RUN-OLD' } } });
    const page = bootPage(state, { status: { runs: [], runsBinding: { state: 'UNAVAILABLE', reason: 'none bound' }, engineering: { state: 'UNAVAILABLE' } } });
    for (let i = 0; i < 10; i++) await Promise.resolve();
    page.sse.listeners.status.forEach((fn) => fn({ data: 'not json{' }));
    const after = page.text('founder-body');
    assert.ok(/Current run/.test(after) || /UNAVAILABLE/.test(after),
      'a malformed push must leave the last honest render standing, not an empty panel');
  });
}

async function atest(name, fn) {
  try { await fn(); passed++; console.log(`ok   ${name}`); }
  catch (e) { console.error(`FAIL ${name}: ${e.message}`); process.exitCode = 1; }
}

asyncTests().then(() => {
  const failedCount = process.exitCode ? 'at least 1' : '0';
  console.log(`${passed} passed, ${failedCount} failed.`);
});
