#!/usr/bin/env node
/**
 * dashboard-slice.test.cjs — proves the visual slice cannot lie.
 *
 * These are static assertions over the slice's source. They are deliberately
 * crude and deliberately paranoid, because the failure they guard against is
 * not a crash — it is a dashboard that looks healthy while the system is not.
 * A timer-driven pulse, a hardcoded "PASS", or a seeded fallback object would
 * all render beautifully and mean nothing.
 *
 * Browser behaviour (real render, failure path, contrast, responsive) is
 * verified separately and recorded in the evidence report; these tests hold the
 * invariants that must never regress unnoticed between those sessions.
 */
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const DIR = path.join(ROOT, 'builder-control', 'dashboard');
const HTML_PATH = path.join(DIR, 'index.html');
const STATE_PATH = path.join(DIR, 'state.js');
// Read fresh each time: a cached copy would let a proof pass against a page
// that no longer exists on disk.
const htmlSrc = () => fs.readFileSync(HTML_PATH, 'utf8');

let passed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log(`ok   ${name}`); }
  catch (e) { console.error(`FAIL ${name}: ${e.message}`); process.exitCode = 1; }
}

const html = fs.readFileSync(HTML_PATH, 'utf8');
// Strip comments so a rule that *describes* a ban is not mistaken for breaking it.
const code = html.replace(/<!--[\s\S]*?-->/g, '').replace(/\/\*[\s\S]*?\*\//g, '');

console.log('AEGIS dashboard slice — invariants');

// ── nothing may animate on a timer ──────────────────────────────────────────
test('no timers anywhere: a pulse that can run without a real event is fake activity', () => {
  for (const banned of ['setInterval', 'setTimeout', 'requestAnimationFrame']) {
    assert.ok(!new RegExp('\\b' + banned + '\\s*\\(').test(code),
      `${banned}( found in executable code — motion must be bound to state, not to time`);
  }
});

test('the only animation is bound to a real ACTIVE state', () => {
  const keyframes = code.match(/@keyframes\s+([\w-]+)/g) || [];
  assert.strictEqual(keyframes.length, 1, `expected exactly 1 keyframes block, found ${keyframes.length}`);
  assert.ok(/\.stage\.is-active\s+\.dot\s*\{[^}]*animation/.test(code),
    'the single animation must be gated on .is-active, which is set only from state');
});

test('reduced motion is honoured and removes the animation', () => {
  assert.ok(/@media\s*\(prefers-reduced-motion:\s*reduce\)/.test(code), 'no reduced-motion block');
  const block = code.slice(code.indexOf('prefers-reduced-motion'));
  assert.ok(/animation\s*:\s*none/.test(block.slice(0, 400)), 'reduced motion must disable the animation');
});

// ── one data path, no seeds ─────────────────────────────────────────────────
test('the slice reads window.AEGIS_STATE and has no fallback seed object', () => {
  assert.ok(/window\.AEGIS_STATE/.test(code), 'must read the projector output');
  assert.ok(!/AEGIS_STATE\s*\|\|\s*\{/.test(code),
    'a `|| {}` fallback would let the page render confidently with no real state');
  assert.ok(/AEGIS_STATE\s*\|\|\s*null/.test(code), 'absence must resolve to null and be handled explicitly');
});

test('state.js is generated, never hand-authored', () => {
  assert.ok(fs.existsSync(STATE_PATH), 'state.js missing — regenerate with aegis-state.cjs --out');
  const s = fs.readFileSync(STATE_PATH, 'utf8');
  assert.ok(/Generated by builder-control\/aegis-state\.cjs/.test(s), 'state.js lacks its generator header');
  assert.ok(/do not edit by hand/i.test(s));
  const json = JSON.parse(s.slice(s.indexOf('{'), s.lastIndexOf('}') + 1));
  assert.deepStrictEqual(json.contract.absences, ['UNAVAILABLE', 'STALE', 'UNVERIFIED']);
});

test('state.js loads BEFORE the renderer, or the renderer would always see nothing', () => {
  // Search the comment-stripped source. The file's own header comment mentions
  // window.AEGIS_STATE while explaining the rule, and matching that prose
  // instead of the executable read made this test fail on correct code.
  const stateTag = code.indexOf('<script src="state.js">');
  const renderer = code.indexOf('var S = window.AEGIS_STATE');
  assert.ok(stateTag !== -1, 'state.js is never loaded');
  assert.ok(renderer !== -1, 'the renderer no longer reads window.AEGIS_STATE');
  assert.ok(stateTag < renderer,
    `state.js (@${stateTag}) must load before the renderer reads it (@${renderer})`);
});

// ── no fabricated values ────────────────────────────────────────────────────
test('no hardcoded status word appears in the markup', () => {
  const body = html.slice(html.indexOf('<body'));
  const markup = body.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<!--[\s\S]*?-->/g, '');
  for (const word of ['PASS', 'HEALTHY', 'VERIFIED', 'COMPLETE']) {
    assert.ok(!new RegExp('>\\s*' + word).test(markup),
      `the literal "${word}" appears in static markup — every status must come from state`);
  }
});

test('no fabricated progress, percentage, uptime or KPI vocabulary', () => {
  for (const banned of ['percentComplete', 'progressPercent', 'uptime', 'Math.random', 'toFixed(0) + \'%\'']) {
    assert.ok(!code.includes(banned), `"${banned}" found — the slice must not synthesise numbers`);
  }
  assert.ok(!/\b\d{1,3}%\s*<\//.test(html), 'a literal percentage is rendered in markup');
});

// ── the three honest absences are all reachable ─────────────────────────────
test('UNAVAILABLE, STALE and UNVERIFIED each have a rendering', () => {
  for (const s of ['UNAVAILABLE', 'STALE', 'UNVERIFIED']) {
    assert.ok(code.includes(s), `${s} has no rendering path`);
    assert.ok(new RegExp('\\.s-' + s + '\\b').test(code) || new RegExp('s-\\$\\{?').test(code),
      `${s} has no state style`);
  }
  assert.ok(/UNAVAILABLE — no AEGIS state is loaded/.test(code),
    'the no-state failure path must be explicit, not an empty page');
});

test('status is never colour-only — every chip carries a glyph and a label', () => {
  assert.ok(/GLYPH\s*=/.test(code), 'no glyph map');
  assert.ok(/c\.appendChild\(el\('span',null,state\)\)/.test(code),
    'the chip must append the state name as text, not rely on colour');
});

// ── 2D is the product ───────────────────────────────────────────────────────
test('no WebGL, no 3D library, no canvas — 2D is authoritative, not a fallback', () => {
  for (const banned of ['webgl', 'three.js', 'THREE.', '<canvas', 'getContext(']) {
    assert.ok(!code.toLowerCase().includes(banned.toLowerCase()),
      `"${banned}" found — the V1 slice must be fully operational without any 3D layer`);
  }
});

// Amended for the switchboard (PKT-20260825-SWITCHBOARD-FOUNDATION): the page
// is now an authenticated control surface, not a file:// static view, and
// legitimately calls same-origin /api/* over fetch()/EventSource. The
// invariant that must never regress is "no CDN, no remote font, no absolute
// URL" — every request stays same-origin and relative.
test('zero external requests: no CDN, no remote font, no absolute URL', () => {
  assert.ok(!/https?:\/\//.test(code.replace(/xmlns="[^"]*"/g, '')),
    'an absolute URL is referenced — this must remain a same-origin control surface');
  for (const m of code.matchAll(/\bfetch\s*\(\s*(['"])([^'"]*)\1/g)) {
    assert.ok(m[2].startsWith('/'), `fetch() must target a same-origin relative path, got: ${m[2]}`);
  }
  for (const m of code.matchAll(/new EventSource\(\s*(['"])([^'"]*)\1/g)) {
    assert.ok(m[2].startsWith('/'), `EventSource must target a same-origin relative path, got: ${m[2]}`);
  }
});

// ── accessibility invariants ────────────────────────────────────────────────
test('keyboard and assistive-tech affordances are present', () => {
  assert.ok(/aria-live="polite"/.test(html), 'no live region');
  assert.ok(/aria-label/.test(code), 'stages carry no accessible label');
  assert.ok(/:focus-visible/.test(code), 'no visible focus style');
  assert.ok(/Escape/.test(code), 'no keyboard dismiss');
  assert.ok(/ArrowDown/.test(code) && /ArrowUp/.test(code), 'no arrow-key traversal along the path');
  assert.ok(/class="sr"[^>]*href="#topology"/.test(html), 'no skip link');
});

test('every state colour token clears 3:1 on the panel background', () => {
  const vars = {};
  const rootBlock = code.slice(code.indexOf(':root{'), code.indexOf('}', code.indexOf(':root{')));
  for (const m of rootBlock.matchAll(/(--[\w-]+):\s*(#[0-9a-fA-F]{6})/g)) vars[m[1]] = m[2];
  const lum = (h) => {
    const c = h.slice(1).match(/../g).map((x) => {
      const v = parseInt(x, 16) / 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
  };
  const ratio = (a, b) => { const l1 = lum(a), l2 = lum(b); const hi = Math.max(l1, l2), lo = Math.min(l1, l2); return (hi + 0.05) / (lo + 0.05); };
  const bg = vars['--bg-1'];
  assert.ok(bg, 'no --bg-1 token');
  for (const t of ['--pass', '--active', '--warn', '--fail', '--blocked', '--stale', '--unknown', '--text-0', '--text-1']) {
    assert.ok(vars[t], `token ${t} missing`);
    const r = ratio(vars[t], bg);
    assert.ok(r >= 3, `${t} (${vars[t]}) is ${r.toFixed(2)}:1 on ${bg} — below the 3:1 this design requires`);
  }
});

// ── VISUAL INTEGRATION RED PROOFS ─────────────────────────────────────────
test('RED: the page renders ELEVEN steps and numbers them', () => {
  const state = JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')
    .replace(/^[\s\S]*?window\.AEGIS_STATE = /, '').replace(/;\s*$/, ''));
  assert.strictEqual(state.engineering.stages.length, 11,
    'the projection the page reads must carry exactly 11 steps');
  assert.ok(/st\.step/.test(htmlSrc()), 'the page must render the contract step number');
  assert.ok(/stepno/.test(htmlSrc()), 'step numbers need their own style hook');
});

test('RED: exactly ONE topology list exists — no duplicated view', () => {
  // A duplicated topology is the classic full-page-duplication bug: two lists
  // render, both look plausible, and they drift apart silently.
  const listIds = (htmlSrc().match(/id="stages"/g) || []).length;
  assert.strictEqual(listIds, 1, `expected one stage list, found ${listIds}`);
  const topo = (htmlSrc().match(/id="topology"/g) || []).length;
  assert.strictEqual(topo, 1, `expected one topology section, found ${topo}`);
  const bodies = (htmlSrc().match(/<body/g) || []).length;
  assert.ok(bodies <= 1, 'more than one body element would duplicate the whole page');
});

test('RED: the page renders SPEND and never a bare zero for unrecorded cost', () => {
  assert.ok(/id="cost"/.test(htmlSrc()), 'a spend panel must exist');
  assert.ok(/S\.cost/.test(htmlSrc()), 'the page must read the cost projection');
  assert.ok(/UNRECORDED/.test(htmlSrc()), 'the page must be able to say UNRECORDED');
  assert.ok(/AT LEAST|totalUsd/.test(htmlSrc()), 'the headline total must be able to say AT LEAST');
  // A hardcoded currency figure would be a fabricated KPI.
  const hardcoded = htmlSrc().match(/USD\s+\d+\.\d+/g) || [];
  assert.deepStrictEqual(hardcoded, [], `hardcoded currency in the page: ${hardcoded.join(', ')}`);
});

test('RED: no external requests, still', () => {
  const ext = htmlSrc().match(/(?:src|href)\s*=\s*["']https?:\/\//g) || [];
  assert.deepStrictEqual(ext, [], 'the page must make zero external requests');
});

test('RED: responsive rules cover narrow and large widths', () => {
  const queries = htmlSrc().match(/@media[^{]+/g) || [];
  assert.ok(queries.length >= 2, `expected responsive breakpoints, found ${queries.length}`);
  assert.ok(/prefers-reduced-motion/.test(htmlSrc()), 'reduced motion must be honoured');
});

test('RED: every rendered stage carries provenance and a reason', () => {
  const state = JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')
    .replace(/^[\s\S]*?window\.AEGIS_STATE = /, '').replace(/;\s*$/, ''));
  for (const st of state.engineering.stages) {
    assert.ok(st.evidence, `step ${st.step} has no evidence source`);
    assert.ok(st.reason, `step ${st.step} has no reason`);
    assert.ok(!/^PASS$/.test(st.state) || st.reason.length > 10,
      `step ${st.step} claims PASS with no substantive reason`);
  }
});

const failedCount = process.exitCode ? 'at least 1' : '0';
console.log(`${passed} passed, ${failedCount} failed.`);
